package co.com.brayanscompany.appanalizatest.vista;

import co.com.brayanscompany.appanalizatest.controlador.RegistroController;
import co.com.brayanscompany.appanalizatest.modelo.RespuestasModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author BRAYAN
 */
public class PresentacionPrueba extends javax.swing.JFrame {

    private final Timer timer;
    private int segundos = 0;
    private int minutos = 0;
    private int tiempoRespuestaSegundos = 0;
    private int id;
    private String numero;
    private String tprueba;
    public String respuestaUsuario;
    private final RegistroController registroController;

    private final ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            segundos++;
            tiempoRespuestaSegundos++;
            if (segundos == 60) {
                minutos++;
                segundos = 0;
            }
            if (minutos == 3 && segundos == 00) {
                JOptionPane.showMessageDialog(
                        null,
                        "Recuerda que solo tienes 5 minutos.");
            }
            if (minutos == 5 && segundos == 00) {
                System.exit(0);
            }
            actualizarTiempo();
        }
    };

    private void actualizarTiempo() {
        String texto = (minutos < 10 ? "0" : "") + minutos + ":"
                + (segundos < 10 ? "0" : "") + segundos;
        tiempo.setText(texto);
    }

    public void setTipoText(String text) {
        tipo.setText(text);
        tprueba = text;
    }

    public void setOpcAText(String text) {
        opcA.setText(text);
    }

    public void setOpcBText(String text) {
        opcB.setText(text);
    }

    public void setOpcCText(String text) {
        opcC.setText(text);
    }

    public void setOpcDText(String text) {
        opcD.setText(text);
    }

    public void setEnunText(String text) {
        enun.setText(text);
    }

    public void setNumeroText(String text) {
        numero = text;
    }

    public void setIdPruebaText(Integer text) {
        id = text;
    }

    /**
     * Creates new form PresentacionPrueba
     */
    public PresentacionPrueba() {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
        timer = new Timer(1000, acciones);
        timer.start();
        this.registroController = new RegistroController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        respuesta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        opcA = new javax.swing.JRadioButton();
        opcB = new javax.swing.JRadioButton();
        opcC = new javax.swing.JRadioButton();
        opcD = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enun = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        tiempo = new javax.swing.JLabel();
        btncontinuar = new javax.swing.JButton();
        derechos = new javax.swing.JLabel();
        company = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tipo.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        tipo.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        jLabel1.setText("Tipo:");

        respuesta.add(opcA);
        opcA.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        opcA.setText("jRadioButton1");

        respuesta.add(opcB);
        opcB.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        opcB.setText("jRadioButton1");

        respuesta.add(opcC);
        opcC.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        opcC.setText("jRadioButton2");

        respuesta.add(opcD);
        opcD.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        opcD.setText("jRadioButton3");

        enun.setEditable(false);
        enun.setColumns(20);
        enun.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        enun.setLineWrap(true);
        enun.setRows(5);
        jScrollPane1.setViewportView(enun);

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        jLabel2.setText("Tiempo:");

        tiempo.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        tiempo.setText("00:00");

        btncontinuar.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        btncontinuar.setText("CONTINUAR");
        btncontinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontinuarActionPerformed(evt);
            }
        });

        derechos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        derechos.setText("Todos los derechos reservados.");

        company.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        company.setText("© 2023 Brayan's Company.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tiempo))
                            .addComponent(opcD)
                            .addComponent(opcC)
                            .addComponent(opcB)
                            .addComponent(opcA)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipo))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(derechos)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(company))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btncontinuar)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tiempo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(opcA)
                .addGap(18, 18, 18)
                .addComponent(opcB)
                .addGap(18, 18, 18)
                .addComponent(opcC)
                .addGap(18, 18, 18)
                .addComponent(opcD)
                .addGap(18, 18, 18)
                .addComponent(btncontinuar)
                .addGap(18, 18, 18)
                .addComponent(company)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(derechos)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncontinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontinuarActionPerformed
        if (opcA.isSelected()) {
            timer.stop();
            respuestaUsuario = opcA.getText().trim();
            registrarRespuesta(respuestaUsuario);
            validarPrueba(tprueba);
            this.dispose();
        } else if (opcB.isSelected()) {
            timer.stop();
            respuestaUsuario = opcB.getText().trim();
            registrarRespuesta(respuestaUsuario);
            validarPrueba(tprueba);
            this.dispose();
        } else if (opcC.isSelected()) {
            timer.stop();
            respuestaUsuario = opcC.getText().trim();
            registrarRespuesta(respuestaUsuario);
            validarPrueba(tprueba);
            this.dispose();
        } else if (opcD.isSelected()) {
            timer.stop();
            respuestaUsuario = opcD.getText().trim();
            registrarRespuesta(respuestaUsuario);
            validarPrueba(tprueba);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Debes seleccionar una respuesta.");
        }
    }//GEN-LAST:event_btncontinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresentacionPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresentacionPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresentacionPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresentacionPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PresentacionPrueba().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncontinuar;
    private javax.swing.JLabel company;
    private javax.swing.JLabel derechos;
    private javax.swing.JTextArea enun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opcA;
    private javax.swing.JRadioButton opcB;
    private javax.swing.JRadioButton opcC;
    private javax.swing.JRadioButton opcD;
    private javax.swing.ButtonGroup respuesta;
    private javax.swing.JLabel tiempo;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
    public boolean registrarRespuesta(String respuestaUsuario) {
        var registroRespuesta = new RespuestasModel(
                numero,
                respuestaUsuario,
                tprueba,
                tiempoRespuestaSegundos,
                id);
        this.registroController.regisRespuesta(registroRespuesta);
        return true;
    }
    
    public boolean validarPrueba(String prueba){
        switch (prueba) {
            case "Ciencias Naturales":
                siguiente(numero, prueba, id);
                break;
            case "Estudios Sociales":
                siguiente(numero, prueba, id);
                break;
            case "Inglés":
                siguiente(numero, prueba, id);
                break;
            case "Lectura Crítica":
                siguiente(numero, prueba, id);
                break;
            case "Matemáticas":
                siguiente(numero, prueba, id);
                break;
            default:
                throw new AssertionError();
        }
    return true;
    }
    
    public boolean siguiente(String numero, String tipoP, Integer id){
        var siguientePreg = new RespuestasModel(
                numero,
                tipoP,
                id);
        this.registroController.sigPregunta(siguientePreg);
        return true;
    }
}
